// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: server/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DevicePlatform int32

const (
	DevicePlatform_DevicePlatformUndefined DevicePlatform = 0
	// 安卓
	DevicePlatform_DevicePlatformAndroid DevicePlatform = 1
	// IOS
	DevicePlatform_DevicePlatformIOS DevicePlatform = 2
	// Web 端
	DevicePlatform_DevicePlatformWeb DevicePlatform = 3
	// 微信内 Web
	DevicePlatform_DevicePlatformWechatWeb DevicePlatform = 4
	// 微信小程序
	DevicePlatform_DevicePlatformWechatMiniApp DevicePlatform = 5
)

// Enum value maps for DevicePlatform.
var (
	DevicePlatform_name = map[int32]string{
		0: "DevicePlatformUndefined",
		1: "DevicePlatformAndroid",
		2: "DevicePlatformIOS",
		3: "DevicePlatformWeb",
		4: "DevicePlatformWechatWeb",
		5: "DevicePlatformWechatMiniApp",
	}
	DevicePlatform_value = map[string]int32{
		"DevicePlatformUndefined":     0,
		"DevicePlatformAndroid":       1,
		"DevicePlatformIOS":           2,
		"DevicePlatformWeb":           3,
		"DevicePlatformWechatWeb":     4,
		"DevicePlatformWechatMiniApp": 5,
	}
)

func (x DevicePlatform) Enum() *DevicePlatform {
	p := new(DevicePlatform)
	*p = x
	return p
}

func (x DevicePlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DevicePlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_server_v1_common_proto_enumTypes[0].Descriptor()
}

func (DevicePlatform) Type() protoreflect.EnumType {
	return &file_server_v1_common_proto_enumTypes[0]
}

func (x DevicePlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DevicePlatform.Descriptor instead.
func (DevicePlatform) EnumDescriptor() ([]byte, []int) {
	return file_server_v1_common_proto_rawDescGZIP(), []int{0}
}

var File_server_v1_common_proto protoreflect.FileDescriptor

var file_server_v1_common_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2a, 0xb4, 0x01, 0x0a, 0x0e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65,
	0x64, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x10, 0x01, 0x12, 0x15,
	0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x49, 0x4f, 0x53, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x57, 0x65, 0x62, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x57, 0x65,
	0x63, 0x68, 0x61, 0x74, 0x57, 0x65, 0x62, 0x10, 0x04, 0x12, 0x1f, 0x0a, 0x1b, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x57, 0x65, 0x63, 0x68, 0x61,
	0x74, 0x4d, 0x69, 0x6e, 0x69, 0x41, 0x70, 0x70, 0x10, 0x05, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x75,
	0x63, 0x61, 0x6e, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_v1_common_proto_rawDescOnce sync.Once
	file_server_v1_common_proto_rawDescData = file_server_v1_common_proto_rawDesc
)

func file_server_v1_common_proto_rawDescGZIP() []byte {
	file_server_v1_common_proto_rawDescOnce.Do(func() {
		file_server_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_v1_common_proto_rawDescData)
	})
	return file_server_v1_common_proto_rawDescData
}

var file_server_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_v1_common_proto_goTypes = []interface{}{
	(DevicePlatform)(0), // 0: server.v1.DevicePlatform
}
var file_server_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_v1_common_proto_init() }
func file_server_v1_common_proto_init() {
	if File_server_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_v1_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_v1_common_proto_goTypes,
		DependencyIndexes: file_server_v1_common_proto_depIdxs,
		EnumInfos:         file_server_v1_common_proto_enumTypes,
	}.Build()
	File_server_v1_common_proto = out.File
	file_server_v1_common_proto_rawDesc = nil
	file_server_v1_common_proto_goTypes = nil
	file_server_v1_common_proto_depIdxs = nil
}
