// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/biu7/gokit/log"
	"github.com/go-kratos/kratos/v2"
	"kratos-gin-template/app/server/internal/biz"
	"kratos-gin-template/app/server/internal/conf"
	"kratos-gin-template/app/server/internal/data"
	"kratos-gin-template/app/server/internal/middleware"
	"kratos-gin-template/app/server/internal/server"
	"kratos-gin-template/app/server/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confBiz *conf.Biz, logger log.Logger) (*kratos.App, func(), error) {
	middlewareMiddleware := middleware.NewMiddleware(confBiz, logger)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	httpServer := server.NewGinServer(confServer, middlewareMiddleware, greeterService, greeterUsecase)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
